<?php
/**
 * Plugin Name:       Imgur Image Upload
 * Description:       Adds possibility to upload images to imgur and use them embedded in Block Editor.
 * Requires at least: 5.9
 * Requires PHP:      8.0
 * Version:           @@VersionNumber@@
 * Author:            Thomas Zwirner
 * Author URI:        https://www.thomaszwirner.de
 * License:           GPL-2.0-or-later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       imgur-image-upload
 *
 * @source https://github.com/j0k3r/php-imgur-api-client
 * @package imgur-image-upload
 */

use ImgurImageUpload\Plugin\Init;
use ImgurImageUpload\Plugin\Installer;

// prevent direct access.
defined( 'ABSPATH' ) || exit;

// do nothing if PHP-version is not 8.0 or newer.
if ( version_compare( PHP_VERSION, '8.0', '<' ) ) {
	return;
}

// set constant with plugin path.
const IMGUR_IMAGE_UPLOAD_PLUGIN = __FILE__;

// set version.
const IMGUR_IMAGE_UPLOAD_PLUGIN_VERSION = "@@VersionNumber@@";

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// initialize the plugin.
add_action(
	'plugins_loaded',
	function () {
		Init::get_instance()->init();
	}
);

/**
 * Run commands on activation of this plugin.
 */
register_activation_hook( IMGUR_IMAGE_UPLOAD_PLUGIN, array( Installer::get_instance(), 'activation' ) );
