<?php
/**
 * Tasks to run during uninstallation of this plugin.
 *
 * @package image-upload-for-imgur
 */

use ImgurImageUpload\Plugin\Uninstaller;

// if uninstall.php is not called by WordPress, die.
if ( ! defined( 'WP_UNINSTALL_PLUGIN' ) ) {
	exit;
}

// prevent direct access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// do nothing if PHP-version is not 8.0 or newer.
if ( version_compare( PHP_VERSION, '8.0', '<' ) ) {
	return;
}

// set constant with plugin path.
const IMAGE_UPLOAD_FOR_IMGUR_PLUGIN = __FILE__;

// get autoloader generated by composer.
require_once __DIR__ . '/vendor/autoload.php';

// run the uninstallation.
Uninstaller::get_instance()->run();
